_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.7
            "8":
                - 2
                - 5
            "12": 0.19.7
            "13": darwin-arm64
batch_size:
    value: 16
bidirectional:
    value: true
cell_type:
    value: LSTM
dropout:
    value: 0.5
emb_dim:
    value: 64
hidden_size:
    value: 512
learning_rate:
    value: 0.001
num_dec_layers:
    value: 3
num_enc_layers:
    value: 3
